
init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\bkbtl
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - Win32

configuration:
  - Debug
  - Release
  - Product

environment:
  matrix:
    - toolchain: msvc13
      project_name: emulator\BKBTL-VS2013.sln
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - toolchain: msvc15
      project_name: emulator\BKBTL-VS2015.sln
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - toolchain: msvc17
      project_name: emulator\BKBTL-VS2015.sln
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - toolchain: msvc19
      project_name: emulator\BKBTL-VS2015.sln
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
